services:
  coop:
    build:
      context: .
      dockerfile: Dockerfile-coop
    container_name: coop
    command:
      - serve
    ports:
      - "9090:80"
    volumes:
      - ./config/server.yml:/etc/ntfy/server.yml
      - coop-data:/var/lib/coop
    environment:
      - TZ=Europe/Vienna
    restart: unless-stopped

volumes:
  coop-data:
